import ADD_DATA from './ADD_DATA'
import ADD_UNWATCHED_DATA from './ADD_UNWATCHED_DATA'
import CHANGE_SELECTED_INDEX from './CHANGE_SELECTED_INDEX'

export default {
  ADD_DATA,
  ADD_UNWATCHED_DATA,
  CHANGE_SELECTED_INDEX
}